{% set name = "psrqpy" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a73964c175a1545cef08def8c07f3503c2f155d757081b00fc068816cfe02f7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - astropy >=3.2  # [py3k]
    - astropy >=2.0,<3.0  # [py27]
    - beautifulsoup4
    - numpy >=1.11
    - packaging
    - pandas >0.21
    - python
    - requests
    - scipy
    - six
    - matplotlib-base
    - ads

test:
  imports:
    - psrqpy

about:
  home: http://www.github.com/mattpitkin/psrqpy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python module for querying the ATNF pulsar catalogue
  doc_url: https://psrqpy.readthedocs.io/en/latest/
  dev_url: http://www.github.com/mattpitkin/psrqpy/
  description: |
    This package provides a way of querying the ATNF pulsar catalogue.

extra:
  recipe-maintainers:
    - mattpitkin
