travis:
  secure:
    BINSTAR_TOKEN: aJ5SmWlh6b8kVlHeL3/rgnjUengb6N3Tg2KmjabyaSF2pgJnh8Tg0HNsJIPJ/RXgFt6GokFsphadd9DsOh8jP7KSa4H28m17Bi51pt9vcpacUHg2NW7bZKzweCLEMsT4ehYhH/XoC77vvoy3lrC472FBK8RoAnOJNlONhnxJrAOWhkdMI+6WIul0MatjfXIUv5oCOXIAKnjLQBU4KNQSfOrOzyON2zxR/lwwdDjOS+98qTuAkG1qcUPHtBDIzPPAvaYSjrijN7uRT+LELjT4gN3d7nXr6Uz6EwTKudbjvWLrpnGgJ8k4BGe6Mav9X+BjViWbNABGxc8PL7qphCT5qARo5u/DJuZI5XzHxXfyTj5xQbHh4nVbCStNItPHWyW7LwEa5x+oqLwglwo4HTjc4lGCvJWVOP6LI4DYdfh57Hm19A4BLF2EWuVJUybiv3eipa5lENV1kQcLm+2nWIjEVsR1dhJY8V4PSFA0TT6vEicZ4Yon6M5BdXk7ap/lNqg398m+AIJIbBgPBdxbXp987tgc8rf46k18LrGqkiyGNkzKoWUECaHNZinVXbeiOafdAmFyY/WugW+c6/ITYsV2uzkHl+g4qV9nF5PHMRJ8yVDhZdB7DyG7i1RMrrEAXJNzHpTc9hTdgtZoorVX3KE3p9qce49NL6vJ1/7FkNqRTAE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
